spring:
  redis:
    host: 139.224.196.88
    port: 6379
    database: 0
    password: Yh199712 #默认为空
    lettuce:
      pool:
        max-active: 20  #最大连接数，负值表示没有限制，默认8
        max-wait: -1    #最大阻塞等待时间，负值表示没限制，默认-1
        max-idle: 8     #最大空闲连接，默认8
        min-idle: 0     #最小空闲连接，默认0
  application:
    name: service-ucenter
  datasource:
    username: khan
    password: Yh199712
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://139.224.196.88:3306/guli_ucenter?serverTimezone=GMT%2B8
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  #spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos服务地址
    sentinel:
      transport:
        port: 8719 # 跟控制台交流的端口，随意指定一个未使用的端口即可
        dashboard: localhost:8080
      eager: true  #取消控制台懒加载，服务启动即可看到sentinel中对当前服务的监控
      filter:
        url-patterns: /** #默认拦截规则为 /*
  session:
    store-type: redis
server:
  port: 8160
mybatis-plus:
  mapper-locations: classpath:com/sysu/guli/service/ucenter/mapper/xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# 设置日志级别
logging:
  level:
    root: info
#开启Feign对Sentinel的支持
feign:
  sentinel:
    enabled: true
wx:
  open:
    # 微信开放平台 appid
    appId: wxed9954c01bb89b47
    # 微信开放平台 appsecret
    appSecret: a7482517235173ddb4083788de60b90e
    # 微信开放平台 重定向url（guli.shop需要在微信开放平台配置）
    redirectUri: http://guli.shop/api/ucenter/wx/callback8160